### ISSUE TITLE
Move Smarter Documentation

### ISSUE THREAD

**Issue by dippi** [3cixty/appchallenge#2]
Hello, we would like to access the services provided by Move Smarter API, but we didn't find any documentation and the platform propts a login form in an unknown language.
Any suggestion about this issue?

**Comment by ragarwa2** [comment]
Hello @Dippi,

We will get back to you on this ASAP. 

regards
/cc'ing @johankoolwaaij

**Comment by johankoolwaaij** [comment]
You can change the language in the top right corner (orange icon) to English.
Next thing that you have to request a developer account from me, or another group admin.
So if you let me know what username and email address to use, I can create you a developer account with access to the documentation.

**Comment by dippi** [comment]
Ok, thank you very much!
It has to be personal or it can be a team account?

Anyway in the showcase application [ExplorMI 360](https://www.3cixty.com) the link [Mobility Profile](https://www.movesmarter.nl/portal/views/personal/profile/heatmap.jsf) open a login form without any explanation or language button.

**Comment by johankoolwaaij** [comment]
Can be both, but please use one app ID for one app.
Let me know a name and an email, and I let you know.

The showcase app should call our login page with a language attribute. Like we explained in the docs of the sensing lib, and in a mail to the explorer developers:

Please find attached an update of the sensing library. It fixes the issue with creating a user account where it complained that no consumer token/secret was set. And it allows one to specify the language in which the login page is shown by changing the call from 

sensingLibrary.displayOAuthView(<domain>)

to

sensingLibrary.displayOAuthView(<domain>, <language>)

Where the supported language values currently are “en” and “nl”:

sensingLibrary.displayOAuthView(“3cixty”, “en”)

**Comment by ragarwa2** [comment]
HouseKeeping: Moving the issue to another Repo as app challenge is over.
