### ISSUE TITLE
Distance in Time

### ISSUE THREAD

**Issue by dippi** [3cixty/appchallenge#3]
We saw on the website that is possible to query the system for POIs or Events within a certain distance in term of time to get there, but we didn't find any documentation related to this feature. Can you point us in the right direction?

**Comment by ragarwa2** [comment]
Hello @Dippi,

We will get back to you on this ASAP.

regards
/cc'ing @giusepperizzo, @ocorcho

**Comment by congkinh** [comment]
That would be done by making sparql queries to the 3cixty platform. @cmbarbu please correct me if I am wrong.

@giusepperizzo, @ocorcho Can you provide some information about sparql queries to do so?

**Comment by ocorcho** [comment]
@jplu and I have been working in the past few days to make those queries easier to generate and faster to run, and we will soon release them.

**Comment by ocorcho** [comment]
For instance, this query gives you the events and hotels that are separated by at most 10 minutes by metro (including walking)
SELECT DISTINCT ?event ?metroEvent ?metroHotel ?hotel ?hotelName
?minDistanceEventMetro ?timeMetro ?minDistanceHotelMetro (
(?timeMetro+?minDistanceEventMetro/6+?minDistanceHotelMetro/6) AS
?totalTime) WHERE
{
  ?hotel http://data.linkedevents.org/def/location#businessType
http://data.linkedevents.org/kos/3cixty/hotel .
  ?hotel ont3:nearestMetroStation ?metroHotel .
  ?hotel ont3:minDistanceNearestMetroStation ?minDistanceHotelMetro .
  ?hotel schema:name ?hotelName .
  ?event a lode:Event .
  ?event ont3:nearestMetroStation ?metroEvent .
  ?event ont3:minDistanceNearestMetroStation ?minDistanceEventMetro .
  ?travelTimeMetro a qb:Observation .
  ?travelTimeMetro ont3:origin ?metroEvent .
  ?travelTimeMetro ont3:destination ?metroHotel.
  ?travelTimeMetro ont3:travelTime ?timeMetro.
  FILTER (?timeMetro+?minDistanceEventMetro/6+?minDistanceHotelMetro/6 < 10)
} 

It can be run on the development SPARQL endpoint already.

**Comment by dippi** [comment]
Thank you, I look forward to see the final release!

Few more questions:
It will be possible to search using busses and trams too?
Are you going to document the changes [here](https://docs.google.com/document/d/1benex0NbsJeTCX1w758d8hBwUkKGA0xLgPaoGxsouSo) or there is any other document?
I tried to use the show case app [ExplorMi 360](https://www.3cixty.com) in developer mode, but when I click "Download Results as JSON" in the SPARQL dialog the server complains about the access token 'null', can you fix it?

**Comment by congkinh** [comment]
@Kai-Dominik can you fix that?

**Comment by ocorcho** [comment]
Hi @dippi, we are not including trams or buses yet, but only metro trips.

**Comment by rtroncy** [comment]
Housekeeping: closing this old issue. Not that the predicates which have been created to find a nearest metro or bus station might end up in a redefined ontology
